### ISSUE TITLE
Obligation's reason parameter and norm id

### ISSUE THREAD

**Issue by igorcadelima** [moise-lang/npl#1]
Hey, devs!

I've noticed that norms obligations may sometimes differ from its definition presented in [1]. According to the paper, an obligation has the format _obligation(a, r, g, d)_, where 

> (...) _r_ is the reason for the obligation (which has to include the id of the norm that originated the obligation).

However, if _r_ is equal to the norm id, it is set to the norm's condition. Otherwise, _r_ remains equal to the norm id which has been passed (expected behaviour). This is done by the following code in the _Norm_ class:

```java 
public Norm createNorm(String id, Literal consequence, LogicalFormula activationCondition) {
    if (!consequence.getFunctor().equals(NormativeProgram.FailFunctor)) {
        if ( ((Literal)consequence.getTerm(1)).getFunctor().toString().equals(id)) {
            consequence.addAnnot(ASSyntax.createStructure("norm", consequence.getTerm(1)));
            consequence.setTerm(1, activationCondition);
        } else {
            consequence.addAnnot(ASSyntax.createStructure("norm", new Atom(id)));                        
        }
    }
    return new Norm(id,consequence,activationCondition);
}
```

In order to be consistent with [1], this code could be replaced with

```java
public Norm createNorm(String id, Literal consequence, LogicalFormula activationCondition) {
    return new Norm(id,consequence,activationCondition);
}
```

With the norm id I can always look the norm up very easily in a database if necessary, which is not the case with the norm condition. 

[1] Hübner, Jomi F., Olivier Boissier, and Rafael H. Bordini. "A normative programming language for multi-agent organisations." Annals of Mathematics and Artificial Intelligence 62.1 (2011): 27-53.

**Comment by jomifred** [comment]
Thanks Igor,

the paper is not evolving as the implementation :-)

r is now the maintenance condition. This change was done to better support prohibitions, but to also support more general cases. E.g.:

      norm npl1: a & v(X) -> obligation(bob,true,g(X),`now`+`1 day`)

the activation is "a & v(X)" and the maintenance condition is "true", in the current version of NPL the above is kept active even if the activation condition does not holds anymore. If activation = maintenance, it works as before.

another example

   norm n2: true  -> prohibition(A,student(_,_), a(V) & V > 30 & setter(a,A), `never`).

the prohibition is kept (for everybody) while there is a student.

**Comment by igorcadelima** [comment]
Thanks, @jomifred ! I guess now I'll have to find a way to obtain the norm id given an obligation :(

**Comment by jomifred** [comment]
The class that represents an obligation (DeonticModality) has a method "getNorm".

**Comment by igorcadelima** [comment]
The problem is that I'm trying to perform this using a Jason agent when it's informed of an obligation creation via observable property.

**Comment by jomifred** [comment]
I have just committed changes in the moise and cartago projects to handle that. JaCaMo agents perceive obligations with a norm annotation:

     obligation(Agt,....,.....,....)[norm(someid),....].

**Comment by igorcadelima** [comment]
Thanks for the effort, @jomifred ! I really appreciate it!

I've run a few tests with the updated code and now the obligation actually looks like 
``` obligation(Agt,....,.....,...., norm_id)[usual_annotations].```

There's an additional parameter for the norm id instead of an annotation. Is it just me?

**Comment by jomifred** [comment]
You have to update also Cartago. The JaCa bridge takes that last term and place it as an annotation.

**Comment by igorcadelima** [comment]
That's exactly the reason! I forgot to perform `gradle clean` before `gradle build`! Thanks again!

**Comment by igorcadelima** [comment]
Sorry to bother you again, @jomifred, but why would someone create an obligation like `obligation(..., normid(param1, ..., paramN), ..., ...)`? I can't think of why someone would create such condition. 

Since you haven't considered the parameters for the annotation as you do in `consequence.addAnnot(ASSyntax.createStructure("norm", consequence.getTerm(1)));`, I started to wonder even more about the need for these parameters.

**Comment by jomifred** [comment]
Hi, the reason for this arguments is to "store" in the obligation relevant information from the instantiation. E.g.:

    norm n1: vl(X) & X > 10 -> obligation(bob,n1(X), g, )

so that the agent can be aware of the X value of its obligation to g.

Regarding the annotation, we have to fix that to include arguments of the norm. Options:
* add a second term in norm annotation. e.g.: [norm(n1,args(10)), ....]
* add a new annotation. e.g. [norm(n1), norm_args(10), ...]
* add annotations in norm id. e.g. [norm(n1)[activation_args(10)],...]

I prefer the last option...

**Comment by jomifred** [comment]
However, only norms where the second argument of the obligation is the norm id supports these feature.... Maybe we have to think in a more general solution. Like to store all the unifications at the norm instantiation moment.

**Comment by jomifred** [comment]
Hi Igor, we have thus committed some changes in all jacamo jars (npl, moise and cartago). Obligation in the agent mind will look like follows

    obligation(
      carol,                                  // who
      not well_formed(sch1),                  // maintenance condition
      committed(carol,mColaborator,sch1),     // what
      1492601349568)                          // deadline
      [...,norm(n3,[...,["S",sch1],["V",0],["Gr",mypaper]])]. // norm

the norm used to create the obligation was `n3` and variable `S` (from the activation condition) value was `sch1`....

**Comment by igorcadelima** [comment]
That was quick!! 🥇 

With these new changes you've made, should I just assume that now there's no reason to do something like ```normid(p1, ..., pN)``` as the user can now retrieve the arguments through the obligation's annotation?

I just tested this new feature and the results actually differ a bit from what you said. The ǹpl program
```
student(bob).
norm n10: student(A)  -> obligation(A,n10(A),g(oal),`never`).
```
produces the belief
```
obligation(bob,student(bob),g,"--")[...,norm(n10,[[A,bob]]),...].
```
Note that **A** isn't surrounded by quotes! So if I have the plan
```
+obligation(A, R, G, D)[norm(NId,[[X,Y]|_])]
   <- .puts("obligation(#{A}, #{R}, #{G}, #{D})[norm(#{NId}, [#{X},#{Y}])]").
```
I get the following output:
```
obligation(bob, student(bob), g, "--")[norm(n10, [bob,bob])]
```

You've probably missed something on the way. I'm pretty sure the bug is here https://github.com/CArtAgO-lang/cartago/commit/f1f6a4ba552dd246c0446c47a61219304520bcdd#diff-a917e8c9b8fa2325052f88da8919e256R574

**Comment by jomifred** [comment]
An intermediate commit had this problem (with variables). The latest certainly uses strings. Maybe you have to clean your gradle repository to force the new version of npl.jar (it is npl that produces that annotation).

**Comment by igorcadelima** [comment]
Yeah, you're right! :)

The problem is that ```gradle clean``` only deletes the build directory and not the jars which have been cached. [By default gradle caches changing modules for 24 hours](https://docs.gradle.org/3.5/userguide/dependency_management.html#sub:dynamic_versions_and_changing_modules). In order to clean the cache I should have entered ```gradle --refresh-dependencies```.
